PROCESSED_DATA_PATH = "/opt/airflow/data/labeled_data_test.csv"
DOCUMENT_STORE_PATH = "/opt/airflow/data/document_store_1.json"
REFINED_PROCESSED_DATA_PATH = "/opt/airflow/data/refined_processed_documents.json"
DOCUMENTS_FILE_PATH = "/opt/airflow/data/document_store_1.json"
PROCESSED_OUTPUT_PATH = "/opt/airflow/data/processed_documents.json"
REFINED_OUTPUT_PATH = "/opt/airflow/data/refined_processed_documents.json"
PROMPT_TEMPLATE_PATH = "/opt/airflow/dags/utils/prompt.txt"