name: Data Preprocessing Tests -- Data Clean

on:
  push:
    paths:
      - 'data_pipeline/dags/utils?data_preprocessing/data_cleaning_pandas.py'
      - 'data_pipeline/tests/test_data_cleaning_pandas.py'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.7'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install -r data_pipeline/requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s data_pipeline/tests/data_preprocessing -p "test_*.py"
