name: Data Preprocessing Tests -- Data Clean

on:
  push:
    paths:
      - 'milestones/data-pipeline-requirements/03-data-preprocessing/staging/dags/utils/data_cleaning.py'
      - 'milestones/data-pipeline-requirements/03-data-preprocessing/staging/tests/test_data_cleaning.py'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.7'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install -r milestones/data-pipeline-requirements/03-data-preprocessing/staging/requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s milestones/data-pipeline-requirements/03-data-preprocessing/staging/tests -p "test_*.py"
